#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x102C2C17498D6B9E (i.tkomiya@gmail.com)
#
Name     : sphinxcontrib-serializinghtml
Version  : 1.1.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/94/c5/ddb8d1d64e03441789078737eea1340667fd82029335d9e7f0805113dd9e/sphinxcontrib-serializinghtml-1.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/94/c5/ddb8d1d64e03441789078737eea1340667fd82029335d9e7f0805113dd9e/sphinxcontrib-serializinghtml-1.1.1.tar.gz
Source99 : https://files.pythonhosted.org/packages/94/c5/ddb8d1d64e03441789078737eea1340667fd82029335d9e7f0805113dd9e/sphinxcontrib-serializinghtml-1.1.1.tar.gz.asc
Summary  : No summary provided
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-serializinghtml-license = %{version}-%{release}
Requires: sphinxcontrib-serializinghtml-python = %{version}-%{release}
Requires: sphinxcontrib-serializinghtml-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
=============================
sphinxcontrib-serializinghtml
=============================

%package license
Summary: license components for the sphinxcontrib-serializinghtml package.
Group: Default

%description license
license components for the sphinxcontrib-serializinghtml package.


%package python
Summary: python components for the sphinxcontrib-serializinghtml package.
Group: Default
Requires: sphinxcontrib-serializinghtml-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-serializinghtml package.


%package python3
Summary: python3 components for the sphinxcontrib-serializinghtml package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sphinxcontrib-serializinghtml package.


%prep
%setup -q -n sphinxcontrib-serializinghtml-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554253879
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-serializinghtml
cp LICENSE %{buildroot}/usr/share/package-licenses/sphinxcontrib-serializinghtml/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-serializinghtml/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
